### ISSUE TITLE
An error occurred while installing lean4-mode

### ISSUE THREAD

**Issue by daniel-ac-martin** [allispaul/spacemacs-lean4-layer#1]
Hello.

When trying to make use of this layer and following the instructions in the README, I encounter the following error:

> An error occurred while installing lean4-mode (error: (error Failed to checkout ‘lean4-mode’: ‘No matching file(s) found in ~/.emacs.d/.cache/quelpa/build/lean4-mode/: (lean4-mode/*.el)’))

I'm guessing that there's something I need to do to install lean4-mode. If that's the case, I wonder if something could be added to the README to make this clear.

**Comment by daniel-ac-martin** [comment]
Oh scratch that, I think that perhaps this is a bug (kind of) in this repo.

More specifically, it seems that leanprover has rearranged their git repositories, and so this repo needs an update.

I _think_ I've got something that works; I'll make a PR.

**Comment by allispaul** [comment]
Looks good to me. Thanks for fixing this!
